# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Warehouses, shelfs and shelfsections
Warehouse.create(name: "Almacen 1")
Warehouse.create(name: "Almacen 2")
caregories = ["Niños", "Adultos Mayores", "Cocina", "Cosecha de lluvia", "Ferreteria", "Papelería", "Electronica"]
19.times do |t|
	Shelf.create(warehouse_id: 1, code: "AN-#{t+1}", category: caregories.sample)	
end
10.time do |t|
	Shelf.create(warehouse_id: 2, code: "AN-#{t+1}", category: caregories.sample)	
end
# Shelf.create(warehouse_id: 1, code: "asdasd", category: "Niños")
# Shelf.create(warehouse_id: 1, code: "asdasd", category: "Adultos mayores")
# Shelf.create(warehouse_id: 1, code: "asdasd", category: "Cosecha de lluvia")
# Shelf.create(warehouse_id: 1, code: "asdasd", category: "Ferreteria")
# Shelf.create(warehouse_id: 1, code: "asdasd", category: "Papelería")
# Shelf.create(warehouse_id: 2, code: "asdasd", category: "Niños")
# Shelf.create(warehouse_id: 2, code: "asdasd", category: "Adultos mayores")
# Shelf.create(warehouse_id: 2, code: "asdasd", category: "Cosecha de lluvia")
# Shelf.create(warehouse_id: 2, code: "asdasd", category: "Ferreteria")
# Shelf.create(warehouse_id: 2, code: "asdasd", category: "Papelería")
ShelfSection.create(shelf_id: 1, number: 1)
ShelfSection.create(shelf_id: 1, number: 2)
ShelfSection.create(shelf_id: 1, number: 3)
ShelfSection.create(shelf_id: 1, number: 4)
ShelfSection.create(shelf_id: 1, number: 5)
ShelfSection.create(shelf_id: 1, number: 6)
ShelfSection.create(shelf_id: 1, number: 7)
ShelfSection.create(shelf_id: 2, number: 1)
ShelfSection.create(shelf_id: 2, number: 2)
ShelfSection.create(shelf_id: 2, number: 3)
ShelfSection.create(shelf_id: 2, number: 4)
ShelfSection.create(shelf_id: 2, number: 5)
ShelfSection.create(shelf_id: 2, number: 6)
ShelfSection.create(shelf_id: 2, number: 7)
ShelfSection.create(shelf_id: 3, number: 1)
ShelfSection.create(shelf_id: 3, number: 2)
ShelfSection.create(shelf_id: 3, number: 3)
ShelfSection.create(shelf_id: 3, number: 4)
ShelfSection.create(shelf_id: 3, number: 5)
ShelfSection.create(shelf_id: 3, number: 6)
ShelfSection.create(shelf_id: 3, number: 7)
ShelfSection.create(shelf_id: 4, number: 1)
ShelfSection.create(shelf_id: 4, number: 2)
ShelfSection.create(shelf_id: 4, number: 3)
ShelfSection.create(shelf_id: 4, number: 4)
ShelfSection.create(shelf_id: 4, number: 5)
ShelfSection.create(shelf_id: 4, number: 6)
ShelfSection.create(shelf_id: 4, number: 7)
ShelfSection.create(shelf_id: 5, number: 1)
ShelfSection.create(shelf_id: 5, number: 2)
ShelfSection.create(shelf_id: 5, number: 3)
ShelfSection.create(shelf_id: 5, number: 4)
ShelfSection.create(shelf_id: 5, number: 5)
ShelfSection.create(shelf_id: 5, number: 6)
ShelfSection.create(shelf_id: 5, number: 7)
ShelfSection.create(shelf_id: 6, number: 1)
ShelfSection.create(shelf_id: 6, number: 2)
ShelfSection.create(shelf_id: 6, number: 3)
ShelfSection.create(shelf_id: 6, number: 4)
ShelfSection.create(shelf_id: 6, number: 5)
ShelfSection.create(shelf_id: 6, number: 6)
ShelfSection.create(shelf_id: 6, number: 7)
ShelfSection.create(shelf_id: 7, number: 1)
ShelfSection.create(shelf_id: 7, number: 2)
ShelfSection.create(shelf_id: 7, number: 3)
ShelfSection.create(shelf_id: 7, number: 4)
ShelfSection.create(shelf_id: 7, number: 5)
ShelfSection.create(shelf_id: 7, number: 6)
ShelfSection.create(shelf_id: 7, number: 7)
ShelfSection.create(shelf_id: 8, number: 1)
ShelfSection.create(shelf_id: 8, number: 2)
ShelfSection.create(shelf_id: 8, number: 3)
ShelfSection.create(shelf_id: 8, number: 4)
ShelfSection.create(shelf_id: 8, number: 5)
ShelfSection.create(shelf_id: 8, number: 6)
ShelfSection.create(shelf_id: 8, number: 7)
ShelfSection.create(shelf_id: 9, number: 1)
ShelfSection.create(shelf_id: 9, number: 2)
ShelfSection.create(shelf_id: 9, number: 3)
ShelfSection.create(shelf_id: 9, number: 4)
ShelfSection.create(shelf_id: 9, number: 5)
ShelfSection.create(shelf_id: 9, number: 6)
ShelfSection.create(shelf_id: 9, number: 7)
ShelfSection.create(shelf_id: 10, number: 1)
ShelfSection.create(shelf_id: 10, number: 2)
ShelfSection.create(shelf_id: 10, number: 3)
ShelfSection.create(shelf_id: 10, number: 4)
ShelfSection.create(shelf_id: 10, number: 5)
ShelfSection.create(shelf_id: 10, number: 6)
ShelfSection.create(shelf_id: 10, number: 7)